version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8
    steps:
      - checkout

      # Set up environment variables
      - run:
          name: Set up environment
          command: |
            echo "NGROK_URL=tcp://0.tcp.in.ngrok.io:17169" >> $BASH_ENV
            echo "DB_USER=sa" >> $BASH_ENV
            echo "DB_PASSWORD=12345" >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Run tests
          command: mvn test
          environment:
            NGROK_URL: $NGROK_URL
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
