version: 2.1

jobs:
 jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.0
    steps:
      - checkout
      - run: java --version

workflows:
  version: 2
  build-workflow:
    jobs:
      - build

# Define when to trigger the workflow
# In this case, trigger on every push to the master branch
# You can adjust this based on your needs
triggers:
  - push:
      branches:
        only:
          - master
