version: 2.1

jobs:
  say-hello:
    docker:
      - image: openjdk:8
    steps:
      - checkout
      - run:
          name: "Build and Test"
          command: "gradle -p KauEvent-clubs :test:testing:test --tests 'AdminTest'"

workflows:
  version: 2
  say-hello-workflow:
    jobs:
      - say-hello
