version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:8  # Use an OpenJDK 8 image

    steps:
      - checkout

      # Install any dependencies your project might have
      # Copy JAR dependencies from the repository
      - run:
          name: Install Dependencies
          command: |
            cp lib/jcalendar-1.4.jar /usr/local/lib/
            cp lib/hamcrest/hamcrest-core-1.3.jar /usr/local/lib/
            cp lib/sqljdbc42.jar /usr/local/lib/
            cp lib/junit-4.13.2-javadoc.jar /usr/local/lib/

  run-tests:
    docker:
      - image: openjdk:8  # Use an OpenJDK 8 image
    steps:
      - checkout
      # Run tests using the JAR file
      - run:
          name: Run Tests
          command: java -jar /usr/local/lib/junit-4.13.2-javadoc.jar -cp .:/usr/local/lib/junit-4.13.2-javadoc.jar:/usr/local/lib/hamcrest-core-1.3.jar:/usr/local/lib/jcalendar-1.4.jar:/usr/local/lib/sqljdbc42.jar org.junit.runner.JUnitCore testing.StudentTest

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - run-tests:
          requires:
            - build
