version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8  # Use a Maven image with JDK 8

    steps:
      - checkout

      # Install any dependencies your project might have
      - run:
          name: Install Dependencies
          command: |
            cp lib/jcalendar-1.4.jar /usr/local/lib/
            cp lib/hamcrest/hamcrest-core-1.3.jar /usr/local/lib/
            cp lib/sqljdbc42.jar /usr/local/lib/
            cp lib/junit_4/junit-4.12.jar /usr/local/lib/

      # Build the project using Maven
      - run:
          name: Build Project
          command: mvn clean install

  run-tests:
    docker:
      - image: maven:3.6-jdk-8  # Use a Maven image with JDK 8
    steps:
      - checkout
      # Run tests using Maven
      - run:
          name: Run Tests
          command: mvn test

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - run-tests:
          requires:
            - build
