version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8

    steps:
      - checkout

      # Build the project using Maven
      - run:
          name: Build Project
          command: mvn clean install

  run-tests:
    docker:
      - image: maven:3.6-jdk-8
    steps:
      - checkout

      # Set up environment variables
      - run:
          name: Set up environment
          command: |
            echo "export NGROK_URL=tcp://0.tcp.in.ngrok.io:17169" >> $BASH_ENV
            echo "export DB_USER=sa" >> $BASH_ENV
            echo "export DB_PASSWORD=12345" >> $BASH_ENV
            source $BASH_ENV

      # Run tests using Maven
      - run:
          name: Run Tests
          command: mvn test
          environment:
            NGROK_URL: $NGROK_URL
            DB_USER: $DB_USER
            DB_PASSWORD: $DB_PASSWORD

      # Store test results
      - store_test_results:
          path: target/surefire-reports

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - run-tests:
          requires:
            - build
