version: 2.1

jobs:
  build:
    docker:
      - image: maven:3.6-jdk-8  # Use a Maven image with JDK 8

    steps:
      - checkout

      # Build the project using Maven
      - run:
          name: Build Project
          command: mvn clean install

  run-tests:
    docker:
      - image: maven:3.6-jdk-8  # Use a Maven image with JDK 8
    steps:
      - checkout

      # Set up environment variables
      - run:
          name: Set up environment
          command: |
            echo "DB_URL=jdbc:sqlserver://0.tcp.in.ngrok.io:19824;databaseName=KAU_Events_Clubs;user=sa;password=12345" >> $BASH_ENV
            echo "DB_USER=sa" >> $BASH_ENV
            echo "DB_PASSWORD=12345" >> $BASH_ENV
            source $BASH_ENV

      # Run tests using Maven
      - run:
          name: Run Tests
          command: mvn test

      # Store test results
      - store_test_results:
          path: target/surefire-reports  # Adjust the path based on your Maven project structure

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
      - run-tests:
          requires:
            - build
