version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:8  # Use an OpenJDK 8 image

    steps:
      - checkout

      # Install any dependencies your project might have
      # Copy JAR dependencies from the repository
      - run:
          name: Install Dependencies
          command: |
            cp jcalendar-1.4.jar /usr/local/lib/
            cp hamcrest-core-1.3-javadoc.jar /usr/local/lib/
            cp sqljdbc42.jar /usr/local/lib/
            cp junit-4.13.2-javadoc.jar /usr/local/lib/

      # Run tests
      - run:
          name: Run Tests
          command: java -cp .:/usr/local/lib/* test.testing.AdminTest.java

workflows:
  version: 2
  build-workflow:
    jobs:
      - build

# Define when to trigger the workflow
# In this case, trigger on every push to the master branch
# You can adjust this based on your needs
triggers:
  - push:
      branches:
        only:
          - master
