version: 2.1

jobs:
  build:
    docker:
      - image: openjdk:8  # Use an OpenJDK 8 image

    steps:
      - checkout

      # Install any dependencies your project might have
      # Assuming the dependencies are in the dependencies directory
      - run:
          name: Install Dependencies
          command: |
            cp dependencies/junit-4.13.2.jar /usr/local/lib/
            cp dependencies/jcalendar-1.4.jar /usr/local/lib/
            cp dependencies/hamcrest-core-1.3-javadoc.jar /usr/local/lib/
            cp dependencies/sqljdbc42.jar /usr/local/lib/

      # Compile the code and tests
      - run:
          name: Compile Project and Tests
          command: javac -cp .:/usr/local/lib/* src/testing/Student.java test/testing/StudentTest.java

      # Run tests
      - run:
          name: Run Tests
          command: java -cp .:/usr/local/lib/*:/usr/local/lib/junit-4.13.2.jar org.junit.runner.JUnitCore test.testing.StudentTest

workflows:
  version: 2
  build-workflow:
    jobs:
      - build

# Define when to trigger the workflow
# In this case, trigger on every push to the master branch
# You can adjust this based on your needs
triggers:
  - push:
      branches:
        only:
          - master
