/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testing;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Abosl
 */
public class userFunctions extends javax.swing.JFrame {

    private String KAU_ID;

    /**
     * Creates new form userFunctions
     */
    public userFunctions() {
        initComponents();
    }
    public userFunctions(String KAU_ID) {
        initComponents();
        this.KAU_ID=KAU_ID;
        userInfoShow( KAU_ID);
        
    }
    
      void userInfoShow(String KAU_ID){
      
           try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
             String url="jdbc:sqlserver://sleman20.database.windows.net:1433;database=KAU_EVENT_AZURE;user=CloudSA8549a509@sleman20;password={Break2020};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;";
            Connection con = DriverManager.getConnection(url);
            String query="select * from student where KAU_ID="+KAU_ID;
         
           PreparedStatement pst = con.prepareStatement(query);
            Statement st= con.createStatement();
            ResultSet rs= st.executeQuery(query);
            String stuName="";
           if(rs.next()){
           stuName+=rs.getString("studentName");
           }
           KAU_IDLabel.setText("Student Name : "+stuName);
           KAULabel.setText("KAU ID : "+KAU_ID);
           
           
           
           
           }
           
           
           
           catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
      
     
      
      }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CLUBS = new javax.swing.JButton();
        EVENTS = new javax.swing.JButton();
        KAU_IDLabel = new javax.swing.JLabel();
        KAULabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        CLUBS.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        CLUBS.setText("Clubs");
        CLUBS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLUBSActionPerformed(evt);
            }
        });

        EVENTS.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 18)); // NOI18N
        EVENTS.setText("Events");
        EVENTS.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EVENTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVENTSActionPerformed(evt);
            }
        });

        KAU_IDLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N

        KAULabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(CLUBS, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(EVENTS, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(KAULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(31, 31, 31)
                            .addComponent(KAU_IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(139, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(KAU_IDLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KAULabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CLUBS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EVENTS, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CLUBSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLUBSActionPerformed
        clubJoinExit field= new  clubJoinExit(KAU_ID);
        
               field.setVisible(true);
               setVisible(false);
    }//GEN-LAST:event_CLUBSActionPerformed

    private void EVENTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVENTSActionPerformed

          eventEnrollDelete field= new  eventEnrollDelete(KAU_ID);
        
              field.setVisible(true);
               setVisible(false);
        
        
    }//GEN-LAST:event_EVENTSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userFunctions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userFunctions().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CLUBS;
    private javax.swing.JButton EVENTS;
    private javax.swing.JLabel KAULabel;
    private javax.swing.JLabel KAU_IDLabel;
    // End of variables declaration//GEN-END:variables
}
